server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Cache-Control "no-store" always;

    location ~ \.(log|txt)$ {
        default_type text/plain;
        charset utf-8;
    }

    location = / {
        try_files /index.html =404;
    }

    location ~ ^/(v[0-9]+)(/.*)?$ {
        try_files $uri $uri/ /$1/index.html =404;
    }
}
