name: Test

on: 
  push:
    branches:
      - 4.0.0-beta.0

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 20.13.1
      uses: actions/setup-node@v1
      with:
        node-version: 20.13.1
    - name: Install dependencies
      run: npm install
    - name: Test
      run: ng test ngx-colors
