name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build:lib
      - name: Build demo
        run: npm run build:examples
      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless
      - name: Lint
        run: npm run lint
